class SimCardRunner
 {
    public static void main(String[] args)
	{
        SimCard ref1 = new SimCard();
		ref1.communication();
        ref1.name = "jio";
        ref1.plan = "Unlimited Data";
        System.out.println("SimCard Name: " +ref1.name);
        System.out.println("The sim card Plan: " +ref1.plan);
        SimCard ref2 = new SimCard();
        ref2.name = "Airtel";
        ref2.plan = "Family Plan";
		System.out.println("SimCard Name: " +ref2.name);
        System.out.println("The sim card Plan: " +ref2.plan);
        SimCard ref3 = new SimCard();
        ref3.name = "Tata";
        ref3.plan = "Prepaid Plan";
        System.out.println("SimCard Name: " +ref3.name);
        System.out.println("The sim card Plan: " +ref3.plan);
        SimCard ref4 = new SimCard();
        ref4.name = "Sprint";
        ref4.plan = "Unlimited Talk & Text";
        System.out.println("SimCard Name: " +ref4.name);
        System.out.println("The sim card Plan: " +ref4.plan);
        SimCard ref5 = new SimCard();
        ref5.name = "Vodafone";
        ref5.plan = "Pay As You Go";
        System.out.println("SimCard Name: " +ref5.name);
        System.out.println("The sim card Plan: " +ref5.plan);
        SimCard ref6 = new SimCard();
        ref6.name = "Orange";
        ref6.plan = "International Plan";
        System.out.println("SimCard Name: " +ref6.name);
        System.out.println("The sim card Plan: " +ref6.plan);
        SimCard ref7 = new SimCard();
        ref7.name = "BSNL";
        ref7.plan = "Student Plan";
        System.out.println("SimCard Name: " +ref7.name);
        System.out.println("The sim card Plan: " +ref7.plan);
        SimCard ref8 = new SimCard();
        ref8.name = "relance";
        ref8.plan = "Unlimited Data and Calls";
        System.out.println("SimCard Name: " +ref8.name);
        System.out.println("The sim card Plan: " +ref8.plan);
        SimCard ref9 = new SimCard();
        ref9.name = "MetroPCS";
        ref9.plan = "Pay As You Go";
        System.out.println("SimCard Name: " +ref9.name);
        System.out.println("The sim card Plan: " +ref9.plan);
        SimCard ref10 = new SimCard();
        ref10.name = "Boost Mobile";
        ref10.plan = "Unlimited Gigs";
        System.out.println("SimCard Name: " +ref10.name);
        System.out.println("The sim card Plan: " +ref10.plan);
        SimCard ref11 = new SimCard();
        ref11.name = "Cricket Wireless";
        ref11.plan = "Unlimited Everything";
        System.out.println("SimCard Name: " +ref11.name);
        System.out.println("The sim card Plan: " +ref11.plan);
        SimCard ref12 = new SimCard();
        ref12.name = "Mobile";
        ref12.plan = "Inner Circle Plan";
        System.out.println("SimCard Name: " +ref12.name);
        System.out.println("The sim card Plan: " +ref12.plan);
        SimCard ref13 = new SimCard();
        ref13.name = "GiffGaff";
        ref13.plan = "Monthly Plan";
        System.out.println("SimCard Name: " +ref13.name);
        System.out.println("The sim card Plan: " +ref13.plan);
        SimCard ref14 = new SimCard();
        ref14.name = "Lycamobile";
        ref14.plan = "International Plan";
        System.out.println("SimCard Name: " +ref14.name);
        System.out.println("The sim card Plan: " +ref14.plan);
        SimCard ref15 = new SimCard();
        ref15.name = "Mint Mobile";
        ref15.plan = "3-Month Plan";
        System.out.println("SimCard Name: " +ref15.name);
        System.out.println("The sim card Plan: " +ref15.plan);
    }
}
